name: flutter_opentok
description: OpenTok Flutter - a library for OpenTok iOS and Android SDKs.
version: 0.0.6
author: Indoor Solutions <genert.org@indoor.solutions>
homepage: https://github.com/ninjasolutions/flutter_opentok

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  json_serializable: ^3.2.0

flutter:
  plugin:
    androidPackage: com.example.flutter_opentok
    pluginClass: FlutterOpentokPlugin
